### ISSUE TITLE
USWDS implementation has inconsistent line lengths

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#45]
it seems like the line length control is inconsistent between standard text and lists or bullets: https://federalist.18f.gov/preview/18f/federalist-docs/uswds/pages/using-federalist/launch-checklist/

**Comment by wslack** [comment]
(note: this issue is not a high priority)

**Comment by juliaelman** [comment]
Pull request submitted #54

**Comment by wslack** [comment]
@juliaelman still seeing issue on https://federalist.18f.gov/preview/18f/federalist-docs/uswds/pages/how-federalist-works/custom-urls/ ... ideas?

**Comment by juliaelman** [comment]
@wslack yup! Sub sub lists need to have this max-width assignment too. I'll take a look!

**Comment by juliaelman** [comment]
Hrmmm... just took a closer look and am not seeing those styles being applied on `ul` or `ol`. The other styles within that sheet ARE working correctly though and wonder if it's an issue with the build.

Can you confirm that the site re-built and deployed correctly after the last PR was merged in?

**Comment by wslack** [comment]
Yep! je-fix_list_width and `uswds` both built correctly.

**Comment by juliaelman** [comment]
@wslack ok - I think we've got it resolved now. The link you used in the above comment points to  https://federalist.18f.gov/. Should it point to https://federalist.fr.cloud.gov/? Just want to make sure I understand clearly which one is the right one for us to use.

It looks like I used `scss` instead of `css` for the override markup. Opening a pull request that should resolve. You can [preview the working instance here](https://federalist.fr.cloud.gov/preview/18f/federalist-docs/je-fix_list_width/pages/how-federalist-works/custom-urls/) 😎

**Comment by wslack** [comment]
@juliaelman it shouldn't matter which preview link we use - jekyll should work the same in both cases. However, https://federalist.fr.cloud.gov/preview/18f/federalist-docs/uswds/ is the new "canonical" link.

I confirmed the fix and we'll plan to merge in the new look soon!

**Comment by juliaelman** [comment]
@wslack can this be closed?

**Comment by wslack** [comment]
YES! Thanks @juliaelman. :)
